/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  sym_identifier = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_comment_token2 = 4,
  aux_sym_comment_token3 = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_void = 8,
  sym_template_chars_single = 9,
  sym_template_chars_double = 10,
  sym_template_chars_single_single = 11,
  sym_template_chars_double_single = 12,
  sym_template_chars_raw_slash = 13,
  sym_block_comment = 14,
  sym_documentation_block_comment = 15,
  sym_source_file = 16,
  sym__top_level_definition = 17,
  sym_type_identifier = 18,
  sym_comment = 19,
  sym_function_signature = 20,
  sym__type = 21,
  aux_sym_source_file_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [sym_identifier] = "identifier",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [aux_sym_comment_token3] = "comment_token3",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_void] = "void",
  [sym_template_chars_single] = "template_chars_single",
  [sym_template_chars_double] = "template_chars_double",
  [sym_template_chars_single_single] = "template_chars_single_single",
  [sym_template_chars_double_single] = "template_chars_double_single",
  [sym_template_chars_raw_slash] = "template_chars_raw_slash",
  [sym_block_comment] = "block_comment",
  [sym_documentation_block_comment] = "documentation_block_comment",
  [sym_source_file] = "source_file",
  [sym__top_level_definition] = "_top_level_definition",
  [sym_type_identifier] = "type_identifier",
  [sym_comment] = "comment",
  [sym_function_signature] = "function_signature",
  [sym__type] = "_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_identifier] = sym_identifier,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [aux_sym_comment_token3] = aux_sym_comment_token3,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_void] = anon_sym_void,
  [sym_template_chars_single] = sym_template_chars_single,
  [sym_template_chars_double] = sym_template_chars_double,
  [sym_template_chars_single_single] = sym_template_chars_single_single,
  [sym_template_chars_double_single] = sym_template_chars_double_single,
  [sym_template_chars_raw_slash] = sym_template_chars_raw_slash,
  [sym_block_comment] = sym_block_comment,
  [sym_documentation_block_comment] = sym_documentation_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__top_level_definition] = sym__top_level_definition,
  [sym_type_identifier] = sym_type_identifier,
  [sym_comment] = sym_comment,
  [sym_function_signature] = sym_function_signature,
  [sym__type] = sym__type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [sym_template_chars_single] = {
    .visible = true,
    .named = true,
  },
  [sym_template_chars_double] = {
    .visible = true,
    .named = true,
  },
  [sym_template_chars_single_single] = {
    .visible = true,
    .named = true,
  },
  [sym_template_chars_double_single] = {
    .visible = true,
    .named = true,
  },
  [sym_template_chars_raw_slash] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_documentation_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_function_signature] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(5);
      if (lookahead == 'v') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_comment_token3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_void);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 2, .external_lex_state = 2},
  [9] = {.lex_state = 2, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 2, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [aux_sym_comment_token3] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [sym_template_chars_single] = ACTIONS(1),
    [sym_template_chars_double] = ACTIONS(1),
    [sym_template_chars_single_single] = ACTIONS(1),
    [sym_template_chars_double_single] = ACTIONS(1),
    [sym_template_chars_raw_slash] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(5),
    [sym_documentation_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym__top_level_definition] = STATE(5),
    [sym_type_identifier] = STATE(9),
    [sym_comment] = STATE(1),
    [sym_function_signature] = STATE(4),
    [sym__type] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [aux_sym_comment_token3] = ACTIONS(3),
    [anon_sym_void] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(5),
    [sym_documentation_block_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__top_level_definition] = STATE(5),
    [sym_type_identifier] = STATE(9),
    [sym_comment] = STATE(2),
    [sym_function_signature] = STATE(4),
    [sym__type] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [aux_sym_comment_token3] = ACTIONS(3),
    [anon_sym_void] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(5),
    [sym_documentation_block_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__top_level_definition] = STATE(5),
    [sym_type_identifier] = STATE(9),
    [sym_comment] = STATE(3),
    [sym_function_signature] = STATE(4),
    [sym__type] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(17),
    [sym_identifier] = ACTIONS(20),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(3),
    [aux_sym_comment_token3] = ACTIONS(3),
    [anon_sym_void] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(5),
    [sym_documentation_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(4), 1,
      sym_comment,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(28), 2,
      sym_identifier,
      anon_sym_void,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [21] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(5), 1,
      sym_comment,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(32), 2,
      sym_identifier,
      anon_sym_void,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [42] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(6), 1,
      sym_comment,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(36), 2,
      sym_identifier,
      anon_sym_void,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [63] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(7), 1,
      sym_comment,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(40), 2,
      sym_identifier,
      anon_sym_void,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [84] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [103] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [119] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [135] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(11), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [151] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [167] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [183] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym_comment,
    ACTIONS(3), 4,
      sym_documentation_block_comment,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [199] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 103,
  [SMALL_STATE(10)] = 119,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 183,
  [SMALL_STATE(15)] = 199,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level_definition, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__top_level_definition, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 3, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_signature, 3, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 4, 0, 2),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_signature, 4, 0, 2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_template_chars_single = 0,
  ts_external_token_template_chars_double = 1,
  ts_external_token_template_chars_single_single = 2,
  ts_external_token_template_chars_double_single = 3,
  ts_external_token_template_chars_raw_slash = 4,
  ts_external_token_block_comment = 5,
  ts_external_token_documentation_block_comment = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_template_chars_single] = sym_template_chars_single,
  [ts_external_token_template_chars_double] = sym_template_chars_double,
  [ts_external_token_template_chars_single_single] = sym_template_chars_single_single,
  [ts_external_token_template_chars_double_single] = sym_template_chars_double_single,
  [ts_external_token_template_chars_raw_slash] = sym_template_chars_raw_slash,
  [ts_external_token_block_comment] = sym_block_comment,
  [ts_external_token_documentation_block_comment] = sym_documentation_block_comment,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_template_chars_single] = true,
    [ts_external_token_template_chars_double] = true,
    [ts_external_token_template_chars_single_single] = true,
    [ts_external_token_template_chars_double_single] = true,
    [ts_external_token_template_chars_raw_slash] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_documentation_block_comment] = true,
  },
  [2] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_documentation_block_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_dart_external_scanner_create(void);
void tree_sitter_dart_external_scanner_destroy(void *);
bool tree_sitter_dart_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_dart_external_scanner_serialize(void *, char *);
void tree_sitter_dart_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dart(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_dart_external_scanner_create,
      tree_sitter_dart_external_scanner_destroy,
      tree_sitter_dart_external_scanner_scan,
      tree_sitter_dart_external_scanner_serialize,
      tree_sitter_dart_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "dart",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
